version: '3.9'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./resources/sql_init:/docker-entrypoint-initdb.d
volumes:
  postgres_data:
